### ISSUE TITLE
Pip install fbprophet is not working

### ISSUE THREAD

**Issue by AAthirasurendran** [facebook/prophet#1939] opened 2021-06-10 11:20 UTC
<img width="1002" alt="Screenshot 2021-06-10 at 4 52 34 PM" src="https://user-images.githubusercontent.com/45350468/121516798-415d8b80-ca0c-11eb-8aeb-c8f39d912cc5.png">

I am not able to install fbprophet. System is macOS Catalina. Python 3.8. I had pip installed pystan 2.18.0.0. Thank you

**Comment by Okroshiashvili** [comment] 2021-06-12 09:43
Hey,

Prophet got a new name and after version 1 changed the way we install it. 

try `pip install prophet`

**Comment by taranggpt6** [comment] 2021-06-16 02:54
I tried pip install fbprophet and also pip install prophet
Still same
![Screenshot 2021-06-16 082208](https://user-images.githubusercontent.com/56186899/122150927-40997f00-ce7c-11eb-813e-38d1d027393a.png)

![Screenshot 2021-06-16 082308](https://user-images.githubusercontent.com/56186899/122150923-3f685200-ce7c-11eb-9f8d-1c486b5ffa1c.png)

**Comment by Okroshiashvili** [comment] 2021-06-16 13:02
> I tried pip install fbprophet and also pip install prophet
> Still same
> ![Screenshot 2021-06-16 082208](https://user-images.githubusercontent.com/56186899/122150927-40997f00-ce7c-11eb-813e-38d1d027393a.png)
> 
> ![Screenshot 2021-06-16 082308](https://user-images.githubusercontent.com/56186899/122150923-3f685200-ce7c-11eb-9f8d-1c486b5ffa1c.png)

I think when you run `pip install prophet` it uses cached version of `fbprophet`. Try creating new clean environment and then run `pip install prophet`

**Comment by taranggpt6** [comment] 2021-06-16 14:23
So now created a new fresh environment with python 3.7 only, ran `pip install prophet` and now getting error 

> pystan._api DLL load failed.

 This error i was already getting in my different env I had created earlier while experimenting prophet installation and now getting same in this new env too.

**Comment by taranggpt6** [comment] 2021-06-16 17:59
After installing MinGW as per 

> https://stackoverflow.com/questions/60388880/import-pystan-api-failedimporterror-dll-load-failed-the-specified-module-cou

was getting the same errors. after running `conda install libpython m2w64-toolchain -c msys2` finally i am able to install prophet using `pip install prophet` but Prophet and FBprophet is same??
I don't see Prophet on official page, there it is Fbprophet only. Can you please clarify?

**Comment by Okroshiashvili** [comment] 2021-06-17 05:54
@taranggpt6 Prophet has an excellent [documentation](https://facebook.github.io/prophet/docs/installation.html)

In your fresh environment, run these two, one by one. Keep the order.

```
pip install pystan==2.19.1.1

pip install prophet
```

**Comment by AAthirasurendran** [comment] 2021-06-22 04:48
> @taranggpt6 Prophet has an excellent [documentation](https://facebook.github.io/prophet/docs/installation.html)
> 
> In your fresh environment, run these two, one by one. Keep the order.
> 
> ```
> pip install pystan==2.19.1.1
> 
> pip install prophet
> ```

Hi, sorry for the delay in reply. I am still getting error. And I want to install greykite 0.1.1 also. I guess for that I need fbprophet only. Thanks in advance.
![Uploading Screenshot 2021-06-22 at 10.16.36 AM.png…]()

**Comment by uncle-vincent** [comment] 2022-03-24 15:31
I also met this problem, and I found it is caused by the -arch option in gcc in this thread https://github.com/giampaolo/psutil/issues/1832.

The solution is
export ARCHFLAGS="-arch x86_64"; pip install pystan==2.19.1.1; pip install prophet

**Comment by miraep8** [comment] 2022-04-27 21:06
> In your fresh environment, run these two, one by one. Keep the order.
> 
> ```
> pip install pystan==2.19.1.1
> 
> pip install prophet
> ```

Just wanted to tune in and say this issue persists.  I am running Windows 10, not Mac OS

**Comment by akosfurton** [comment] 2022-06-27 14:33
This issue has been further cleaned up in Prophet v1.1

No more need for pystan, the models are precompiled in the build

`pip install --upgrade prophet` to upgrade to 1.1

**Comment by hasmit-coder** [comment] 2022-07-16 03:24
> > I tried pip install fbprophet and also pip install prophet
> > Still same
> > ![Screenshot 2021-06-16 082208](https://user-images.githubusercontent.com/56186899/122150927-40997f00-ce7c-11eb-813e-38d1d027393a.png)
> > ![Screenshot 2021-06-16 082308](https://user-images.githubusercontent.com/56186899/122150923-3f685200-ce7c-11eb-9f8d-1c486b5ffa1c.png)
> 
> I think when you run `pip install prophet` it uses cached version of `fbprophet`. Try creating new clean environment and then run `pip install prophet`
> 
> Or in the same environment run `pip install prophet --no-cache-dir`

Thank you. It worked with -> pip install prophet --no-cache-dir

**Comment by WardBrian** [comment] 2023-10-12 13:38
Closing due to PyStan no longer being a dependency of `prophet`

**Closed by WardBrian** 2023-10-12 13:38 UTC
Labels: py, mac, install
