### ISSUE TITLE
thoughts on possible model extensions

### ISSUE THREAD

**Issue by josaum** [facebook/prophet#389] opened 2017-12-20 17:37 UTC
Hey everyone. First, thanks for the awesome work with this package!

As I am working more and more with it, I started wondering if:

1 - would it be possible to extend the main STAN model to incorporate uncertainty regarding lag effects of the regressors. So if for instance we are using holidays as additional regressors for a sales forecasting task, we might want to estimate no only how much it will impact, but also when (i.e. how many days/weeks before the actual holiday date) it will impact.
Example model within STAN: https://github.com/stan-dev/example-models/blob/master/misc/garch/koyck.stan

2 - how to model the occurrence of zeroes in the series: currently the only workaround that I have found is to build a separate ML model that predicts (1 or 0) whether there will be or not a sale for any given time, and the use it as an external regressor within Prophet. But of course it would be much more consistent to incorporate this 'feature' within the prophet model itself (maybe as a mixture model).

Any thoughts on these capabilities within the stan/prophet framework?

Thanks!

**Comment by bletham** [comment] 2017-12-22 23:23
These are interesting ideas.

1. We do something along the lines of the "Unstructured estimation" part here: https://en.wikipedia.org/wiki/Distributed_lag . The user specifies a maximum range of lag values (the lower_window and upper_window) and then each day in that range is added as a feature in the regression. However, Prophet is not an auto-regressive model, it's a plain regression, and so we don't have the multicollinearity issue described there. I'm not sure what the extension of the structured approaches would be to the Prophet model, if you have thoughts I'd be curious to hear them. Generally the idea with the current approach is that one can specify reasonably large lower_ and upper_ windows, and then use the l2 regularization on the coefficients to shrink to just the days needed to model the holiday effect, thereby learning the correct lag.

2. Is the idea that there is some propensity to purchase, and we want to use Prophet to model that propensity? So maybe the Prophet model would be the rate in e.g. a Poisson process?

**Comment by bletham** [comment] 2018-02-01 21:35
I'm going to close this since I don't think there are any action items here.

**Closed by bletham** 2018-02-01 21:35 UTC

**Comment by mathDR** [comment] 2018-08-30 15:06
Hey @bletham we just gave a StanCon2018 talk on "self-tuning holidays" that allows for automatic fitting of holidays in Stan.  I think this might be a great feature that answers the ask ( number 1.) in this issue.  Let me know if you are interested in us pushing a PR

Best

Dan

**Comment by vhpietil** [comment] 2018-08-30 15:14
I was just listening to this interesting talk at Stancon and would be very happy to see this implemented in Prophet framework :)

**Comment by bletham** [comment] 2018-09-11 04:44
@mathDR sounds interesting, I'd be interested to see this. Is there a paper / video of the talk? We actually are in the process of pushing out some new holiday functionality (built-in collections of major holidays by country,  817f0306a45c7c5014b804877e87d32c22435f58) so we can see how it would mesh with that.

**Comment by mathDR** [comment] 2018-09-11 18:11
@bletham I think they are posting video of the talk this week:  http://mc-stan.org/events/stancon2018Helsinki/. Alex Braylan gave the talk on Thursday.  We also submitted a python notebook with the full stan code and examples, and I will link to that when it is available.
