### ISSUE TITLE
If using all scalar values, you must pass an index

### ISSUE THREAD

**Issue by brandonmichaelhunter** [facebook/prophet#339] opened 2017-10-26 14:36 UTC
Running 

- Python 3.5 64 bits on Windows 7

- Visual C++ 2015 Redistributable (x64) - 14.0.24210

Provided below is my code and where I'm getting the error: "If using all scalar values, you must pass an index"
# Python
import pandas as pd
import numpy as np
from fbprophet import Prophet

df = pd.read_csv('example_wp_peyton_manning.csv', header=0, parse_dates=[0], squeeze=True )
df['y'] = np.log(df['y'])
m = Prophet()
m.fit(df);
m.daily_seasonality = True
future = m.make_future_dataframe(periods=365, freq='M')
future.tail()

forecast = m.predict(future) -- ERROR here
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
m.plot(forecast);

If I used a modify version by adding the df.head() statement, then I get the same error but at a different location:
import pandas as pd
import numpy as np
from fbprophet import Prophet

df = pd.read_csv('example_wp_peyton_manning.csv', header=0, parse_dates=[0], squeeze=True )
df['y'] = np.log(df['y'])
df.head()
m = Prophet()
m.fit(df);
m.daily_seasonality = True
future = m.make_future_dataframe(periods=365, freq='M') - #Error
future.tail()

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
m.plot(forecast);

Please help identify how I can resolve my issue.

**Comment by bletham** [comment] 2017-11-02 23:43
This seems to be a pandas issue but I'm not exactly sure what would be causing it. Could you post the full stacktrace for this error so I can see what line of code it is coming from?

**Comment by bletham** [comment] 2017-12-22 22:01
I'm going to close this for now but if you can post a stacktrace I might be able to help debug this.

**Comment by github-hdp** [comment] 2018-02-05 20:42
Identical issue here... same setup, just trying to get the sample code up and running:

Traceback (most recent call last):
  File "D:/Dropbox (R Squared Capital)/Harry/New Model/python/fbProphetTest.py", line 18, in <module>
    forecast = m.predict(future)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\fbprophet\forecaster.py", line 875, in predict
    seasonal_components = self.predict_seasonal_components(df)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\fbprophet\forecaster.py", line 1006, in predict_seasonal_components
    components, 'extra_regressors', list(self.extra_regressors.keys()))
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\fbprophet\forecaster.py", line 1042, in add_group_component
    new_comp['component'] = name
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 2504, in __setitem__
    self._set_item(key, value)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 2573, in _set_item
    self._ensure_valid_index(value)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 2550, in _ensure_valid_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index

**Comment by github-hdp** [comment] 2018-02-06 12:56
Sorry.. my code is actually a smidge different... same error though.


import pandas as pd
import numpy as np
from fbprophet import Prophet


df = pd.read_csv('../fbprophet/example_wp_peyton_manning.csv')
df['y'] = np.log(df['y'])
df.head()

m = Prophet()
#m.daily_seasonality=True
m.fit(df)

future = m.make_future_dataframe(periods=365)
#future = m.make_future_dataframe(periods=365, include_history=True, freq="d")
future.tail()
print(future)
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

m.plot(forecast)

m.plot_components(forecast)

**Comment by bletham** [comment] 2018-02-08 19:37
This must be an issue specific to a particular version of pandas. I am not able to replicate this issue in pandas 0.22 or 0.18.1.

Could you try this code and see if it produces the same error:
```
import pandas as pd
new_comp = pd.DataFrame({'col': [], 'component': []})
new_comp['component'] = 'test'
```

And then could you also check what version of pandas you have (`pd.__version__`)?

**Comment by github-hdp** [comment] 2018-02-09 18:37
That's got it, thanks!  

I was running  pandas 0.21.0rc1, then upgraded to 0.22

On 0.22 the sample runs fine, but on 0.21.0rc1 the sample generates an error: 

C:\Users\hp\AppData\Local\Programs\Python\Python35\python.exe C:/Users/hp/AppData/Local/Programs/Python/Python35/Lib/site-packages/fbprophet/test.py
Traceback (most recent call last):
  File "C:/Users/hp/AppData/Local/Programs/Python/Python35/Lib/site-packages/fbprophet/test.py", line 6, in <module>
    new_comp['component'] = 'test'
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 2504, in __setitem__
    self._set_item(key, value)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 2573, in _set_item
    self._ensure_valid_index(value)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\frame.py", line 2550, in _ensure_valid_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index

Process finished with exit code 1

**Comment by bletham** [comment] 2018-02-10 01:50
Great, we'll make sure this works in 0.21.0rc1 also.

**Comment by Joycechidi** [comment] 2018-05-14 21:28
Hi,
I am using pandas 0.22.0 and encountered the same problem.
Traceback (most recent call last):
  File ".\separateSheets.py", line 24, in <module>
    df = pd.DataFrame(output_data, columns= ['Date', 'Time', 'Build Number', 'Jobname'])
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 426, in _init_dict
    index = extract_index(list(data.values()))
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 6202, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index

What could be causing this error. Thanks for your urgent attention.

Joyce

**Comment by bletham** [comment] 2018-05-16 01:33
@Joycechidi it seems from the stacktrace that you are encountering this issue outside of fbprophet (which is the package that this issue tracker is for). I think this discussion here will probably be helpful: https://stackoverflow.com/questions/17839973/construct-pandas-dataframe-from-values-in-variables . It's hard to tell exactly what the issue is just from your traceback, but I would guess that `output_data` is a dictionary with numbers as values, when it needs to have lists as values. Check the stackoverflow link for more.

**Comment by bletham** [comment] 2018-05-28 22:00
This works in 0.21.0 and 0.21.1, so it is just the release candidate that had the bug. Pandas has too frequent breakages for me to be motivated to work around all of them (see also #256), so I'm going to go ahead and not work around this, and ask people to stick to a release version.

**Closed by bletham** 2018-05-28 22:00 UTC
Labels: bug
