### ISSUE TITLE
Problems inserting a data frame with holidays

### ISSUE THREAD

**Issue by larissadecarvalho** [facebook/prophet#1813] opened 2021-02-10 14:02 UTC
I was trying to input a data frame with the holidays, but I got the following error:

 _Error in make_holiday_features(m, df$ds, holidays) : 
  Holiday "holiday name" does not have a consistent prior scale specification_

As I saw at the documentation, the prior scale is an optional, but it seems that doesn't work without that.

I tried to add a column with the prior scale in the data frame, but doesn't work too. 

Bellow the method that I'm using to input the holidays. 

Note: The name of the data frame is Holidays as well. 

`model <- prophet::prophet(dataset, holidays = holidays, fit = FALSE)`

**Comment by bletham** [comment] 2021-02-11 01:03
Can you show `head(holidays)`? If you leave the `prior_scale` column out entirely (like in https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#modeling-holidays-and-special-events) then it should work.

**Comment by larissadecarvalho** [comment] 2021-02-11 12:59
Hello, thanks for the quick response. 

I tried without pior_scale column but still doesn't work. 

![image](https://user-images.githubusercontent.com/22121982/107639503-b59b4480-6c4f-11eb-861d-ba19fa997481.png)

**Comment by bletham** [comment] 2021-03-01 19:56
Hm I'm really not sure what might be happening, could you provide code that I can run to reproduce your issue?

**Comment by larissadecarvalho** [comment] 2021-03-02 12:54
Sure!

`modeltrain_z4 <- function(dataset) {

  names(dataset) <- c("ds", "y")
  model <- prophet::prophet(dataset, fit = FALSE)
  model <- prophet::prophet(dataset, holidays = holidays, fit = FALSE)
  model <- prophet::fit.prophet(model, dataset)

  return(model)
}
`

**Comment by bletham** [comment] 2021-03-02 21:28
OK thanks for the clean repro.

The issue is that there are a bunch of NAs at the bottom of the holiday dataframe. If you remove those, it works.

We should either be filtering those out or raising a more clear error so let's leave this open until that gets fixed.

**Comment by bletham** [comment] 2021-03-03 23:44
2e9f831 fixes this by raising an error in this situation where there are NAs in the holidays dataframe.

**Comment by bletham** [comment] 2021-04-02 23:56
The fix has been pushed to CRAN and pypi in the new v1.0 (with the new package name, prophet)

**Closed by bletham** 2021-04-02 23:56 UTC
Labels: bug, ready
