### ISSUE TITLE
Prophet is not picking up the Initial Points Prediction?

### ISSUE THREAD

**Issue by andymancodes** [facebook/prophet#617] opened 2018-07-18 07:38 UTC
![xxxxxx](https://user-images.githubusercontent.com/37308037/42866934-a83047c6-8a8b-11e8-947a-48ef6e804421.PNG)
Hi,

I have a dataset of about 250 days, I am trying to use it for forecasting. I have carefully tuned it to upto 4% MAPE but the issue is that, I am still not able to make the initial points fit. I really want to understand why is it happening and what other tunings I could do (I have a monthly seasonality, multiplicative and an extra regressor for weekends).

Please take a look at the below data. Thanks!
![image](https://user-images.githubusercontent.com/37308037/42866884-86baa2c6-8a8b-11e8-8f3c-7fe56332cb3b.png)

**Comment by vhpietil** [comment] 2018-07-18 08:12
The weekly seasonality on the beginning is different from the rest of the data. Distance between weekends and weekdays seem to be larger than in the rest of the data. It is impossible to capture that with constant weekly seasonality.

If you have extra regressors in every weekend, it does not make any difference. It still makes every weekend similar. If you have some weekends that are different from other, you could put regressors on those weekends to fit them better.

Does you data contain any holidays that affect the values? There are some strange values in your data.

**Comment by andymancodes** [comment] 2018-07-20 04:08
@vhpietil yes, putting extra regressors on weekends didn't help. I am not sure about the holidays. Am trying quarterly cycles as well.

**Comment by bletham** [comment] 2018-08-02 00:28
Like @vhpietil said, the issue is that the weekly seasonality in the model is static (same size every week) while here it is clearly stronger at the start of the time series than at the end. There isn't really a good way to learn dynamic seasonality in Prophet (see #391). Also like @vhpietil said if you thought this was a holiday effect that would repeat at the end of the year then you could make a holiday for each of the weekend days around this time of year and then it would learn it, but without a full year of data it's hard to know if that would be reasonable or not.

I don't think there is much more to do here than @vhpietil's suggestions so I'm going to close the issue, but feel free to re-open if you have other questions along this line.

**Closed by bletham** 2018-08-02 00:28 UTC
