### ISSUE TITLE
setting new holiday,but "AttributeError: 'NoneType' object has no attribute 'max'"

### ISSUE THREAD

**Issue by kikizxd** [facebook/prophet#358] opened 2017-11-15 09:10 UTC
My data is bigger when every 28th and 1st ,and it's like "holiday".

ds | y
-- | --
2017/08/24 | 811
2017/08/25 | 671
2017/08/26 | 572
2017/08/27 | 701
2017/08/28 | 10867
2017/08/29 | 586
2017/08/30 | 412
2017/08/31 | 368

**code:**

**#import package**
import pandas as pd
import numpy as np
import os
from fbprophet import Prophet

**#read data**
train =r'D:\python\learn\28_hd_data.csv'
pwd = os.getcwd()
os.chdir(os.path.dirname(train))
df = pd.read_csv(os.path.basename(train))
os.chdir(pwd)
df['y'] = np.log(df['y'])

**#set new holiday**
holiday_1 = pd.DataFrame({
  'holiday': 'holiday_1',
  'ds': pd.to_datetime(['2017-08-28', '2017-09-28', '2017-10-28']),
  'lower_window': 0,
  'upper_window': 0,
})
holiday_2 = pd.DataFrame({
  'holiday': 'holiday_2',
  'ds': pd.to_datetime(['2017-08-01', '2017-09-01', '2017-10-01', '2017-11-01']),
  'lower_window': 0,
  'upper_window': 0,
})
holidays = pd.concat((holiday_1,holiday_2))

**#predict**
m = Prophet(holidays=holidays)
future = m.make_future_dataframe(freq='D',periods=30)
m.fit(df)
forecasts = m.prophet.predict(future)
m.plot(forecasts).show()
m.plot_components(forecasts).show()

**error like this**

Anyone knows why? thank U

**Comment by kikizxd** [comment] 2017-11-15 09:13
**error:**
Traceback (most recent call last):

  File "<ipython-input-37-cd18813488ba>", line 36, in <module>
    future = m.make_future_dataframe(freq='D',periods=30)

  File "D:\python\lib\site-packages\fbprophet\forecaster.py", line 1215, in make_future_dataframe
    last_date = self.history_dates.max()

AttributeError: 'NoneType' object has no attribute 'max'

**Comment by kikizxd** [comment] 2017-11-15 09:16
**error:**
Traceback (most recent call last):

File "", line 36, in 
future = m.make_future_dataframe(freq='D',periods=30)

File "D:\python\lib\site-packages\fbprophet\forecaster.py", line 1215, in make_future_dataframe
last_date = self.history_dates.max()

**AttributeError: 'NoneType' object has no attribute 'max'**

**Comment by bletham** [comment] 2017-11-17 00:57
Thanks for pointing this out. The issue is that you need to run `make_future_dataframe` _after_ `m.fit(df)` so that it knows where the history dates are.

This error needs to be caught with a message to first fit the model.

**Comment by bletham** [comment] 2018-01-23 00:05
I'm going to keep this open until I add better error messaging about this.

**Comment by bletham** [comment] 2018-02-02 00:22
fixed in 7b9acd953fd4a12ff5fe44a7d4909808cfdcca51

**Comment by bletham** [comment] 2018-06-07 18:20
Fix pushed with v0.3.

**Closed by bletham** 2018-06-07 18:20 UTC
Labels: bug, ready
