### ISSUE TITLE
Importing xgboost.xgb before Prophet causes ValueError exception

### ISSUE THREAD

**Issue by KennedyMurphy** [facebook/prophet#1206] opened 2019-11-05 18:35 UTC
If xgboost.xgb is imported before fgprophet.Prophet, then a ValueError exception is thrown for certain time series. The below example throws the following exception:

```
import xgboost as xgb
from fbprophet import Prophet
import pandas as pd

temp = pd.DataFrame({
    'ds': [
        '2016-11-27T00:00:00.000000000', '2016-12-04T00:00:00.000000000',
        '2016-12-11T00:00:00.000000000', '2016-12-18T00:00:00.000000000',
        '2016-12-25T00:00:00.000000000', '2017-01-01T00:00:00.000000000',
        '2017-01-08T00:00:00.000000000', '2017-01-15T00:00:00.000000000',
        '2017-01-22T00:00:00.000000000', '2017-01-29T00:00:00.000000000',
        '2017-02-05T00:00:00.000000000', '2017-02-12T00:00:00.000000000',
        '2017-02-19T00:00:00.000000000', '2017-02-26T00:00:00.000000000',
        '2017-03-05T00:00:00.000000000', '2017-03-12T00:00:00.000000000',
        '2017-03-19T00:00:00.000000000', '2017-03-26T00:00:00.000000000',
        '2017-04-02T00:00:00.000000000', '2017-04-09T00:00:00.000000000',
        '2017-04-16T00:00:00.000000000', '2017-04-23T00:00:00.000000000',
        '2017-04-30T00:00:00.000000000', '2017-05-07T00:00:00.000000000',
        '2017-05-14T00:00:00.000000000', '2017-05-21T00:00:00.000000000',
        '2017-05-28T00:00:00.000000000'
    ],
    'y': [
        420., 0., 0., 0., 0., 1260., 0., 0., 0., 420., 840., 420., 420., 0.,
        840., 0., 0., 840., 0., 420., 0., 0., 420., 420., 0., 420., 0.
    ]
})

temp['ds'] = pd.to_datetime(temp['ds'])
m = Prophet()
m.fit(temp)
```

```
ValueError: normal_lpdf: Scale parameter is 0, but must be > 0!
```

The exception is not thrown when imports are done in the following order:
```
from fbprophet import Prophet
import xgboost as xgb
import pandas as pd
```

Below are the versions of XGB and Prophet:
xgboost==0.90
fbprophet==0.5

**Comment by bletham** [comment] 2019-11-07 23:06
hm I don't get this same issue, also with xgboost 0.90 and fbprophet 0.5. Could you give the full traceback for the error? It looks like it's coming from pystan but I'd like to verify. Could you check your pystan version? Mine is 2.19.0.0

**Comment by KennedyMurphy** [comment] 2019-11-12 16:27
Here is the stack trace following m.fit():

```>>> m.fit(temp)
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:fbprophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
INFO:fbprophet:n_changepoints greater than number of observations.Using 20.

Initial log joint probability = 11.871
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kennedymurphy/depromo/lib/python3.7/site-packages/fbprophet/forecaster.py", line 1131, in fit
    params = model.optimizing(**args)
  File "/Users/kennedymurphy/depromo/lib/python3.7/site-packages/pystan/model.py", line 581, in optimizing
    ret, sample = fit._call_sampler(stan_args)
  File "stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_8060362021483799319.pyx", line 1046, in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_8060362021483799319.StanFit4Model._call_sampler
  File "stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_8060362021483799319.pyx", line 406, in stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_8060362021483799319._call_sampler
ValueError: normal_lpdf: Scale parameter is 0, but must be > 0!
```

Versions:
```
% pip freeze | grep fb                 
fbprophet==0.5
% pip freeze | grep xgb                
xgboost==0.90
% pip freeze | grep pystan             
pystan==2.19.1.1
% python --version
Python 3.7.2
```

If you cannot recreate the issue on your end it may be an issue caused by my environment. If that is the case I will close the ticket unless I can recreate it on another machine.

**Comment by bletham** [comment] 2020-01-27 22:53
I tried this on a 2nd machine with the same package versions and didn't get the error.
There is a known issue where depending on the import order there can be issues between fbprophet and BigQuery (#363). The issue there was ultimately something with pystan, which I suspect is the case here. You could try:
```
import xgboost as xgb
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```
and see if that produces the error.

**Comment by bletham** [comment] 2020-02-21 19:45
I'm not able to reproduce this and so will close it, but if others run into the issue please re-open and we can try to dig further.

**Closed by bletham** 2020-02-21 19:45 UTC
